# Generated by Django 4.2.5 on 2023-09-26 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='BookAuthor',
        ),
    ]
