# Generated by Django 4.2.4 on 2023-10-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_description'),
        ('book', '0009_bookauthor_book_author'),
    ]

    operations = [
    ]
