# Generated by Django 4.2.4 on 2023-10-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_merge_20231002_1338'),
        ('book', '0010_merge_20231003_2126'),
    ]

    operations = [
    ]
