# Generated by Django 4.2.4 on 2023-08-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('type', models.CharField(choices=[('Admin', 'admin'), ('User', 'user')], default='user', max_length=5)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('sex', models.CharField(choices=[('Masculino', 'masculino'), ('Feminino', 'feminino'), ('Outro', 'outro')], max_length=9)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
