# Generated by Django 4.2.4 on 2023-09-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=5),
        ),
    ]
