# Generated by Django 4.2.4 on 2023-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_category_id_remove_book_category_and_more'),
        ('user', '0004_userfavorites_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, through='user.UserFavorites', to='book.book'),
        ),
    ]
