# Generated by Django 4.2.4 on 2023-09-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_purchase_userpurchase_purchaseitem_purchase_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ManyToManyField(through='user.UserPurchase', to='user.user'),
        ),
    ]
