# Generated by Django 4.2.4 on 2023-09-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_purchase_user_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='purchases',
            field=models.ManyToManyField(blank=True, through='user.UserPurchase', to='user.purchase'),
        ),
    ]
