# Generated by Django 4.2.4 on 2023-09-25 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_category_id_remove_book_category_and_more'),
        ('user', '0008_remove_purchase_user_user_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, through='user.UserFavorites', to='book.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='purchases',
            field=models.ManyToManyField(blank=True, null=True, related_name='purchases', through='user.UserPurchase', to='user.purchase'),
        ),
    ]
