# Generated by Django 4.2.4 on 2023-10-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_purchase_purchaseitem_purchase_books_purchase_user'),
        ('user', '0009_purchase_user_alter_user_favorites_and_more'),
    ]

    operations = [
    ]
