# Generated by Django 4.2.4 on 2023-10-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
