# Generated by Django 4.2.4 on 2023-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
    ]
