# Generated by Django 4.2.4 on 2023-10-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_merge_20231003_2126'),
        ('user', '0014_purchase_address_purchase_status'),
    ]

    operations = [
    ]
