# Generated by Django 4.2.4 on 2023-10-16 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_merge_20231016_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='freight',
        ),
        migrations.AddField(
            model_name='purchase',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='Pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='user.purchase'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
