# Generated by Django 4.2.4 on 2023-10-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_user_cart_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='user.purchase'),
        ),
    ]
